### ISSUE TITLE
ECDSA using Z

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol-specs#1]
Do you think the following would be worthwhile to add?

[ECDSA using Z](https://github.com/weaversa/CryptolSpecifications/tree/master/ECDSA)

**Comment by atomb** [comment]
Absolutely! This looks really cool.

**Comment by weaversa** [comment]
I'm mostly finished now. What is the best way to integrate a spec here? Is there a style guide?

**Comment by atomb** [comment]
We don't have any style guide at the moment. The main guideline we have in mind is that we're hoping to share code between algorithms when it makes sense. We'd be happy to accept a pull request, or to incorporate the code ourselves (though that would likely happen a little less quickly).
