### ISSUE TITLE
Clean up uses of `coerceSize`

### ISSUE THREAD

**Issue by mccleeary-galois** [GaloisInc/cryptol-specs#101]
Now that https://github.com/GaloisInc/cryptol/pull/1713 has been merged, some use cases of `coerceSize` should be able to be removed from `cryptol-specs`, particularly in ML-KEM, e.g. https://github.com/GaloisInc/cryptol-specs/blob/049f57d681c3a45469d8b533a944be9dd42988d7/Primitive/Asymmetric/Cipher/ML-KEM/specification.cry#L198

**Comment by rod-chapman** [comment]
If we make this change now, are we happy that cryptol-specs will depend on a nightly build of Cryptol, rather than a formally tagged release?  Put another way - should we create a release 3.2 of Cryptol before updating this repo?

**Comment by mccleeary-galois** [comment]
`cryptol-specs` current target is `nightly` at the moment,

https://github.com/GaloisInc/cryptol-specs/blob/049f57d681c3a45469d8b533a944be9dd42988d7/.github/workflows/ci.yml#L13

However, the CI overhaul in the roadmap plans to test `cryptol-specs` against `nightly` and a predetermined set of releases of `cryptol`. 

I am okay with holding off on this ticket until the new CI is in place (we can start cutting tickets over here for that as well).

**Comment by rod-chapman** [comment]
OK... sounds good

**Comment by marsella** [comment]
Oops, I missed the discussion on this issue about waiting to fix. I have a branch that adds all the fixes, I'll just leave it as a draft PR until we're ready to stabilize CI and the version of cryptol with this fix in it. See #107.

**Comment by mccleeary-galois** [comment]
Discussed this internally and we came to the conclusion of releasing a new Cryptol version and having cryptol-specs CI target nightly and the most recently released version of `Cryptol` as a starting point.
