### ISSUE TITLE
Add efficient twin-mul implementation for NIST P-curves

### ISSUE THREAD

**Issue by marsella** [GaloisInc/cryptol-specs#103]
Currently, twin multiplication on elliptic curves (`[a]P + [b]Q` for scalars `a`, `b` and curve points `P` and `Q`) is implemented naively for the NIST P-curves. We should implement the optimized algorithm in [the NIST EC doc](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=e1b05e600bfcdeecf8555bc9948483c5fbbdd478) (Routine 2.2.12

Note that this issue is for the `PFEC` implementation. There is a sample implementation of twin-mul in `Primitive/Asymmetric/Signature/ECDSA/ECDSA.cry` that we should draw from. There's also an implementation in `Common/EC/p384_ec_mul.cry` but it looks pretty different from the coding style in the rest of the implementation.

- [ ] Implement twin mult!
- [ ] Do a quick benchmark to see how much faster it is?

**Comment by kiniry** [comment]
If this issue is closed, then its subtasks should be closed, @marsella and @mccleeary-galois.
