### ISSUE TITLE
Update MLKEM for FIPS 203 FINAL

### ISSUE THREAD

**Issue by rod-chapman** [GaloisInc/cryptol-specs#116]
Final issue of FIPS 203 was made public on 13th August 2024. There are functional changes.

This issue to track updates to Cryptol model, test cases, and so on.

**Comment by kiniry** [comment]
Wooo!

**Comment by rod-chapman** [comment]
I have this updated on a branch of my fork. Testing against the new KATs now. I will open a PR as soon as possible.

**Comment by rod-chapman** [comment]
FIPS 203 FINAL has a group of new input-data validation functions that are required. I have them done in SPARK. Would anyone like to have a crack at them in Cryptol?

**Comment by mccleeary-galois** [comment]
> FIPS 203 FINAL has a group of new input-data validation functions that are required. I have them done in SPARK. Would anyone like to have a crack at them in Cryptol?

We have a need to train up some folks in Cryptol so this might be a good issue for them to take a crack at. @marsella

**Comment by rod-chapman** [comment]
The SPARK implementations start here:
 https://github.com/awslabs/LibMLKEM/blob/1bec368e14ecd79625a18b8b787cfe2f595814f0/spark_ada/src/mlkem.adb#L1951

It should be too hard to turn those back into Cryptol...

**Comment by rod-chapman** [comment]
OK - KATs look good. I have opened:
 https://github.com/GaloisInc/cryptol-specs/pull/131

**Comment by rod-chapman** [comment]
We still need those new input validation functions though.
