### ISSUE TITLE
Module names in McEliece_KEM directory are all wrong

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol-specs#12]
There are two problems here:
1. The files under the `McEliece_KEM` directory don't use hierarchical module names like the rest of the `cryptol-specs` repo does.
2. There are lots of case-mismatches between the filenames (e.g. the lowercase `McEliece/low-level/gf.cry`) and the module names used in the source files (e.g. the uppercase `module GF` and `import GF`).

**Comment by yav** [comment]
The capitalization of the files should be fixed now
