### ISSUE TITLE
Remove coerceSize from MLKEM

### ISSUE THREAD

**Issue by rod-chapman** [GaloisInc/cryptol-specs#126]
Following resolution of Issue #1489 and the release of Cryptol 3.2.0, the use of coerceSize in ML-KEM/specification.cry is no longer needed and can be removed.

**Comment by mccleeary-galois** [comment]
This is probably a duplicate of #101, but we should ensure that both PRs open are indeed covering all of the uses of `coerce-size`

**Comment by rod-chapman** [comment]
Actually.. I already opened PR #127 didn't I...

**Comment by mccleeary-galois** [comment]
> Actually.. I already opened PR #127 didn't I...

No worries, I was more implying we should just ensure that all of the changes in #127 are captured in #107 or vice versa.

**Comment by rod-chapman** [comment]
OK. I guess you could merge my commits, then merge those over to whatever branch is being used for #107. Please go ahead.

**Comment by marsella** [comment]
This was closed by #107.
