### ISSUE TITLE
Bring encoding and compression functions in ML-KEM up to gold standard

### ISSUE THREAD

**Issue by marsella** [GaloisInc/cryptol-specs#144]
There are some differences between our implementation and [the FIPS 203 spec](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.pdf) that should be addressed to make it very obvious that our spec is correct. There are several missing properties and the encode/decode functions need to be a bit more explicit to map correctly onto the spec.

The current state of encoding / decoding is a little confusing. The spec defines `ByteEncode` and `ByteDecode` , which basically convert between `d`-bit integers and byte arrays, for $d \in [1, 12]$. The behavior for `d=12` is slightly different than for other values; instead of 12-bit integers, the conversion is to integers mod `q`.  We can implement this using numeric constraint guards (we do actually need multiple implementations). Right now there are several different encode / decode functions that I think are used to separate these cases (see `DecodeBytes` that returns an `ell`-bit integer and `Decode` that returns an array of integers mod `q`)

Also, the spec overloads the function names (both for encode/decode and compression) and applies them to both single inputs and arrays of inputs; we can't overload names in Cryptol so we need an alternate solution. Since this is an issue across multiple functions (including these and NTT at least), I propose we add suffixes to the applications on arrays `_Vec` and on matrices `_Mat`. So we might have the following functions:
```
Compress : {d} (fin d) => Z q -> [d]
Compress_Vec : {d, n} (fin d) => [n](Z q) -> [n][d]
Compress_Mat : {d, n, m} (fin d) => [n][m](Z q) -> [n][m][d]
```

These are the specific tasks I identified while auditing / making #143. If other details arise while making these changes, please note them in the comments.

- [x] Add the bit/byte conversion example on P21 as a property
- [x] Add the missing compression correctness property from P21. We have one, but we still need to add "Compress_𝑑(Decompress_𝑑(𝑦)) = 𝑦 for all 𝑦 ∈ ℤ_2𝑑 and all 𝑑 < 12."
- [x] Write a single `ByteEncode` that uses numeric constraint guards to handle all cases of `d` (the output type will be something like `Z (min (2^^d) q)`)
- [x] Add properties for encoding and decoding
	- [x] For `d < 12` they are each others' inverse on all inputs, and in each direction (e.g. `encode (decode x) == x` and `decode (encode x) == x`. 
	- [x] For `d == 12`, decode isn't 1-1 so there's something a little funky about the inverses -- I think there are values where `encode (decode x) != x`. (see section 7.2). Figure out what the appropriate properties to prove in this case are.
	- [x] In the docstrings, either prove the `< 12` property for all values of `d` or just for the ones used in the spec (`d_u`, `d_v`, 1).
- [x] The implementation currently has a "spec" version and an optimized version for decode. There's a property showing that the two decode versions are equivalent (this is good! and gold standard!) For encode, the spec version is missing and there is no equivalence property. These should be added.
- [x] Replace `'` and `''` versions of the compression and encoding functions with `_Vec` and `_Mat` versions for clarity.
- [x] Replace uses of the old encode / decode and compress / decompress functions with the new verisons.
- [x] Add any documentation needed to clarify all the functions and their uses and assumptions.

**Comment by kiniry** [comment]
Another fantastic issue write-up.  Thanks for modeling great methodology so well, @marsella.

**Comment by marsella** [comment]
I spent some time poking at the bits-to-bytes conversion functions to try to understand what's happening. The spec is explicit that bit vectors are in little-endian order, and based on the conversion function it implies that byte vectors should also be in LSB order. Currently, our implementation represents bit vectors in little-endian, and byte vectors in big-endian / MSB order.

How do the tests still pass? Byte -> bit conversions are applied to three types of data in the spec:
1. A message passed from the caller
2. The output of the PRF (SHAKE256)
3. Keys and ciphertexts that have been passed through `ByteEncode` (and within that, the bit -> byte conversion)

We also know that SHAKE128 returns MSB bits by default (now, previously it didn't but the implementation accounts for that by calling `map reverse` on the bits) and that Cryptol's default interpretation of literals, like the messages passed in the tests, is MSB. This means that, as long as the Bit->Byte and Byte->Bit conversions are each others inverse (which they are!), the spec will still work even if the byte ordering does not match what's in the NIST spec.
