### ISSUE TITLE
Suspicious algorithm in ECDSA.cry

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/cryptol-specs#21]
https://github.com/GaloisInc/cryptol-specs/blob/3887d96d68c6dcf20eaa50ed061abcce14367d76/Primitive/Asymmetric/Signature/ECDSA/ECDSA.cry#L90

I'm no expert in this algorithm, but as best I can tell this decompression function is supposed to check the front two bits of `S` to determine the sign of `Ry`, which should tell you which root of `t0` to take.  However, the parity of `c` here is compared to `t1`, which doesn't seem right.

@weaversa, looks like you added this code, and there doesn't seem to be any properties exercising this function.  Are you confident this is doing the right thing? (I ask because I'm finding places where code will need to be updated for the next Cryptol version).

**Comment by weaversa** [comment]
What I wrote follows the spec verbatim. 

https://apps.nsa.gov/iaarchive/customcf/openAttachment.cfm?FilePath=/iad/library/ia-guidance/ia-solutions-for-classified/algorithm-guidance/assets/public/upload/Mathematical-routines-for-the-NIST-prime-elliptic-curves.pdf&WpKes=aF6woL7fQp3dJiEQ8FmaMkxJkSBDSjzBGrjzq2#page21

However, @weeknightmvp and I did find a few bugs In that doc when we worked through it. ???

**Comment by weaversa** [comment]
I will ask the author, next chance I get.

**Comment by weaversa** [comment]
I am kind of wondering why I use both `b` and ``` `b ```.

**Comment by robdockins** [comment]
FYI, that's a dead link for me

**Comment by weaversa** [comment]
https://apps.nsa.gov/iaarchive/library/ia-guidance/ia-solutions-for-classified/algorithm-guidance/mathematical-routines-for-the-nist-prime-elliptic-curves.cfm

**Comment by weaversa** [comment]
How about that?

**Comment by robdockins** [comment]
That works, thanks

**Comment by robdockins** [comment]
For reference, the spec for the algorithm in question is:

```
1: c ← 2 most significant bits of S
2: Rx ← n least significant bits of S
3: t ← Rx^3 − 3Rx + b (mod p)
4: t1 ← √t0 (mod p) {use modular square root routine from chapter 3}
5: if t1^2 != t0 then
6:   return ERROR {no such point}
7: end if
8: if t1 == c (mod2) then
9:   Ry ← t1
10: else
11:  Ry ← p−t1
12: end if
```

I think in line 8, the intention is to test if `t1` is equivalent-mod-2 to `c`, i.e., that `t1` has the same parity as `c`.  This, think, should be rendered `t1%2 == c%2` in Cryptol, rather than `t1 == c%2` as above.

**Comment by weaversa** [comment]
Oh, I bet you’re right!

**Comment by robdockins** [comment]
Indeed, it seems using \`b is an error, and the module parameter `b` should be used instead. Likewise, I can verify that the p192 test point named `T` doesn't correctly round trip with the test as-is (after fixing the `b` issue).  If we change the test to `t1%2 == c%2`, both `S` and `T` correctly round trip.

Random round-trip testing (generating points from the generator `G`) also seems to confirm that this is the correct test.

**Comment by weaversa** [comment]
I believe this is fixed
