### ISSUE TITLE
ECDSA should use new `prime` type constraint

### ISSUE THREAD

**Issue by weaversa** [GaloisInc/cryptol-specs#33]
https://github.com/GaloisInc/cryptol-specs/blob/f60e109f176d10d6868ddf4cd029c80d1addf2f2/Primitive/Asymmetric/Signature/ECDSA/ECDSA.cry#L74

rather:

```
 type constraint Constraints a = (fin a, prime a, a >= 4) 
```

**Comment by marsella** [comment]
This was added in #96!
