### ISSUE TITLE
Missing open source license

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/cryptol-specs#39]
The github page for this repository displays no license for the project; also there is no `LICENSE` file inside the repository itself. An explicit open source license will enable anyone to freely and uniformly use any combination of files from this repository. This will become even more important as we start to collect contributions from various third parties.

**Comment by alext-w** [comment]
Ditto to the above. I'm interested in trying Cryptol out and using these ready-made specs would be quite beneficial, however right now some files don't have a license at all (e.g. HKDF), many say "Use freely for educational purposes", which effectively prevents any production use.

Is there any plan with regard to the license clarification and unification for the whole repo?

**Comment by RyanGlScott** [comment]
Thanks for reminding me of this issue. I'll opt to close this now that #68 has landed, but please re-open this is there is still something unclear license-wise.
