### ISSUE TITLE
Add post-quantum cryptol specs and documentation

### ISSUE THREAD

**Issue by andrew-bivin** [GaloisInc/cryptol-specs#50]
COS:

- [x] Add All four NIST finalist algorithms
- [x] Add README describing the algorithms/any info a user should know
- [x] README(s) should include a section with "known issues" (e.g. Falcon spec issues, etc.)
  - [ ] Add corresponding issues for these caveats
- [x] Copy over issues from old project repo to this repo
- [x] Add table of contents to top-level README
- [x] Add appreciations for original spec authors

**Comment by mariosge** [comment]
@andrew-bivin For adding and moving issues, perhaps we can do it after we merge? So that the issues correspond to main branch.
