### ISSUE TITLE
Kyber and known answer tests

### ISSUE THREAD

**Issue by ramsdell** [GaloisInc/cryptol-specs#55]
I tested the Kyber Cryptol spec for decryption using the known answer tests from NIST.  To do it, I created an AWK script that reads the NIST responses and generates a Cryptol batch file.  Submitting that file to Cryptol shows that for every one of the 100 known answer tests, the answers disagree.

There are three attachments.  The first one is the AWK script (you have to remove the .txt extension).  Second one is a bash script that sets the CRYPTOLPATH (you have to remove the .txt extension and make it executable). The final file is a transcript that shows how to create the batch file and the results of running it.

[kat.awk.txt](https://github.com/GaloisInc/cryptol-specs/files/11602017/kat.awk.txt)
[cryptol-specs.txt](https://github.com/GaloisInc/cryptol-specs/files/11602028/cryptol-specs.txt)
[kyber.txt](https://github.com/GaloisInc/cryptol-specs/files/11602052/kyber.txt)

**Comment by andrew-bivin** [comment]
Assigned to @mariosge and @bboston7 just for visibility. We'll triage soon.

Thanks @ramsdell for submitting the issue!

**Comment by ramsdell** [comment]
Try generating the batch file using the attached version of the kat AWK script.  The batch file generated makes the answers match.  I think there is something wrong with BytesToBits.

[katrev.awk.txt](https://github.com/GaloisInc/cryptol-specs/files/11628310/katrev.awk.txt)

**Comment by mariosge** [comment]
Thank you for submitting this issue @ramsdell ! Such review is super useful. I created a PR that solves it here:
https://github.com/GaloisInc/cryptol-specs/pull/58
