### ISSUE TITLE
Questions about p384_field_mod

### ISSUE THREAD

**Issue by hadasz** [GaloisInc/cryptol-specs#8]
I'm trying to figure out how the implementation of [p384_field_mod ](https://github.com/GaloisInc/cryptol-specs/blob/master/Common/EC/p384_field.cry#L51) relates to Routine 3.2.11 in [Mathematical routines for the NIST prime elliptic curves](https://github.com/GaloisInc/cryptol-specs/blob/master/Primitive/Asymmetric/Signature/ECDSA/doc/10.1.1.204.9073.pdf). 

So far, I understand that instead of first appending the 32-bit-word partitions and _then_ adding them together, the reference implementation does the addition first and then the appending. I see that the rows in the implementation line up with the columns in Routine 3.2.11 , where the first row is the right-most column, the second row is the next column to the left, and so on. 

I also see that the d_i are the bits that are left over from carrying.

What I don't understand is line 86 which checks to see if d11@0 is a 1. I assume this has something to do with signed word extension happening in the chop function? Why does this imply a potential underflow?

Also - is there a reference for the explanation and proof of how this algorithm accomplishes reduction modulo p?

Thanks

**Comment by atomb** [comment]
I think @joehendrix might know the answer to this.

**Comment by hadasz** [comment]
Okay - after thinking about it more, I have a little more of an understanding. I now know that Cryptol does subtraction modular 2^x for values of type [x], and so all the subtraction here is mod 2^64, which explains why d_i would have its most significant digit as 1 in the case of a negative number. 

I'm still confused as to why having one of the sums being negative would imply underflow. I also could still use a resource on why this algorithm works for reduction modulo p. 

Thanks so much

**Comment by marsella** [comment]
We removed the p384 implementation of elliptic curves and replaced it with a version in `Common/EC/PrimeField/PFEC.cry` (see #113). The new version has references to all the resources I used to implement and understand the algorithms. I think it uses somewhat different approaches than what this question is about anyway.

Closing this issue for now.
